### ISSUE TITLE
Missing IPython.html when installed and trying to use on docker image

### ISSUE THREAD

**Issue by jason-ogaard** [lydian/jupyterlab_multicontents_templates#1]
When I install this extension on either the jupyterlab-base docker image or the jupyterlab-minimal image I get the same issue. I can see the templates tab, but I cannot see any actual templates or template groups. Here is what I see when I run the ```jupyter server extension list``` command

![image](https://github.com/lydian/jupyterlab_multicontents_templates/assets/3477027/ca688790-cbdf-4fd9-b4cc-c566a88ab19b)

Of course I checked to ensure that IPython was actually installed, it is

![image](https://github.com/lydian/jupyterlab_multicontents_templates/assets/3477027/3739910b-b0f0-405a-905b-f3578b99cce7)

I have edited the /etc/jupyter/jupyter_notebook_config.py file with the following config (taken from the examples folder):

```
c.JupyterLabMultiContentsTemplates.template_folders = {
    "lessons": {
        "manager_class": "IPython.html.services.contents.filemanager.FileContentsManager",
        "kwargs": {
            "root_dir": "/home/jovyan/lessons"
        },
    },
    "utilities": {
        "manager_class": "IPython.html.services.contents.filemanager.FileContentsManager",
        "kwargs": {
            "root_dir": "/home/jovyan/lessons"
        },
    },
}
```
I've also added the import of IPython at the top of the config file. I'm quite certain that this is the correct configuration file as I can add other options there and they'll get picked up (like ```c.NotebookApp.token = ''``` to remove the request for a on start up). The folders listed in the above config do exist and there are .ipynb files in them. What am I missing?

Edit: it was pointed out on [stackoverflow](https://stackoverflow.com/questions/76222920/jupyterlab-extension-could-not-be-found-no-module-named-ipython-html-are-yo?noredirect=1#comment134454487_76222920) that this issue is likely due to a compatibility issue with newer versions of IPython. This extension attempts to import ```IPythonHandler``` from ```IPython.html.base.handlers``` and no such module exists at that location. A fix would be to import the handler from the new location.

**Comment by adrian-bacon-fico** [comment]
@lydian my PR that you merged fixes this issue.  Both @jason-ogaard and I are on the same dev team.

**Comment by jason-ogaard** [comment]
Hi Lydian,

Could you please accept the latest PR and push a new version of the
multicontents templates package out to PyPi? If you can't we're going to
have to make our own and push it.

Thanks,
~Jason

**Comment by lydian** [comment]
ah, cool. I'll just add you both as collaborator. So that you don't need to wait for me. Given that I am quite busy these days.

**Comment by lydian** [comment]
I've just merged your PR, and create a new tag which automatically upload a new version to PYPI. 
 Thanks for fixing this.  
 
 @jason-ogaard wondering if you can also help me update the CHANGELOG ?  THanks

**Comment by jason-ogaard** [comment]
Thanks Lydian,

We’ll get the change log updated

~ Jason
________________________________

**Comment by lydian** [comment]
Thanks so much

**Comment by jason-ogaard** [comment]
Issue is fixed by PRs 2, 3, and 4
